### ISSUE TITLE
[IDEA] module_repository

### ISSUE THREAD

**Issue by bjoliveau** [OCA/oca-custom#4]
Maybe you can have a look on this addon :
https://github.com/Smile-SA/odoo_addons/tree/8.0/smile_module_repository

I launched this idea during i was working in this company and my colleagues wrote it.

The description inside the **openerp**.py is quite short ;-)

This addon aims to connect with several VCS, follow code you downloaded and use each module you get as a product.

The final aim (not present in this addon) is to use a product (a module) in all flow you want (ie : knowledge base, recipe or customer deliveries...).

**Comment by pedrobaeza** [comment]
This is not related with the repository. Maybe with Github connector...
