### ISSUE TITLE
Missing 13.0 metafiles

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-custom#42]
pre-commit stuff and so on is not here.

**Comment by pedrobaeza** [comment]
@sbidoul I can't either push them as I don't have permission in this repository. When are you going to restore core maintainer permissions?

**Comment by sbidoul** [comment]
Core maintainer permissions are ok. For some reason, all teams were removed from this project. I added the core maintainer team again.

**Comment by pedrobaeza** [comment]
OK, thanks, then pushing the metafiles myself.
