### ISSUE TITLE
 [IDEA] complementary addon for graphic view on module

### ISSUE THREAD

**Issue by bjoliveau** [OCA/oca-custom#9]
Maybe you can have a look on this addon :
https://github.com/Smile-SA/odoo_addons/tree/8.0/smile_module_graph

My previous colleagues wrote and use it.

This addon should be use for a graphic view base, for example and seems to be a nice complement for "oca-custom" and "repository_module" 

You have a wizard to select criterias with ascendant and/or descendant depends
![001_201610_39a](https://cloud.githubusercontent.com/assets/1226478/19073025/f493dd4e-8a38-11e6-9e35-b3b0a3f878fe.png)

Then, you get a graph.
In this example, i selected a l10n
![001_201610_d3c](https://cloud.githubusercontent.com/assets/1226478/19073040/fc388126-8a38-11e6-92fe-638c9e262973.png)

**Comment by pedrobaeza** [comment]
It can be interested indeed. We'll study it to be integrated.
